feat: adding `Career` link to user menu
edx/frontend-component-header-edx pull request #375
Opened 2023-05-09 22:08 UTC by krishatcher

### Description:

Adding a new link to the User Menu for logged-in users. This will redirect the user to the "Career Resource Center" or "CRC".

**Note that this PR should not go to Production until 31 May 2023, the launch date for the CRC.**

### JIRA:

[CAMS-1](https://2u-internal.atlassian.net/browse/CAMS-1)

2023-05-19 06:30 UTC, Syed-Ali-Abbas-Zaidi requested changes

2023-05-19 06:30 UTC, Syed-Ali-Abbas-Zaidi commented on src/Header.jsx
> +  const careerItemContent = `${intl.formatMessage(messages['header.user.menu.career'])} <span className="badge badge-warning">${intl.formatMessage(messages['header.user.menu.newAlert'])}</span>`;
`Career New` is not appearing as per the design given in [CAMS-1](https://2u-internal.atlassian.net/browse/CAMS-1).

![Screenshot 2023-05-19 at 11 10 58 AM](https://github.com/edx/frontend-component-header-edx/assets/88369802/67c8bdbd-37c6-4d80-bf91-060835a11d8e)

2023-05-19 13:53 UTC, leangseu-edx commented on src/Header.jsx
> +  const careerItemContent = `${intl.formatMessage(messages['header.user.menu.career'])} <span className="badge badge-warning">${intl.formatMessage(messages['header.user.menu.newAlert'])}</span>`;
```suggestion
  const careerItemContent = (${intl.formatMessage(messages['header.user.menu.career'])}<span className="badge badge-warning">${intl.formatMessage(messages['header.user.menu.newAlert'])}</span>);
```

2023-05-19 21:14 UTC, Syed-Ali-Abbas-Zaidi commented on src/Header.jsx
> +  const careerItemContent = `${intl.formatMessage(messages['header.user.menu.career'])} <span className="badge badge-warning">${intl.formatMessage(messages['header.user.menu.newAlert'])}</span>`;
Hi @krishatcher, As we have removed the [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) we don't need the `$` sign anymore. That is one of the reasons that lint is failing. You can replace it with the given code snippet:

`const careerItemContent = <>{intl.formatMessage(messages['header.user.menu.career'])}<span className="badge badge-warning">{intl.formatMessage(messages['header.user.menu.newAlert'])}</span></>;`

By utilizing the aforementioned code snippet, the rendering of `Career New` is now being executed correctly. However, the overall design still appears to be lacking.

<img width="1669" alt="Screenshot 2023-05-20 at 2 01 38 AM" src="https://github.com/edx/frontend-component-header-edx/assets/88369802/15c2ae81-029a-4d70-8f55-e3a48edfaae2">

2023-05-23 14:20 UTC, Syed-Ali-Abbas-Zaidi requested changes

2023-05-23 14:20 UTC, Syed-Ali-Abbas-Zaidi commented on src/Header.jsx
> +  const careerItemContent = <>{intl.formatMessage(messages['header.user.menu.career'])}&nbsp;&nbsp;<Badge className="px-2 mx-2" variant="warning">{intl.formatMessage(messages['header.user.menu.newAle
Currently, the badge is appearing as a rectangle. There is a boolean prop `pill` in the `Badge` component that will make it look like a pill.

`<Badge className="px-2 mx-2" variant="warning" pill>`

<img width="384" alt="Screenshot 2023-05-23 at 7 13 13 PM" src="https://github.com/edx/frontend-component-header-edx/assets/88369802/be864e4b-f891-4d65-9c6f-a7d951267b82">

Adding a `pill` prop will make it look exactly like the design given in the ticket.

<img width="345" alt="Screenshot 2023-05-23 at 7 16 48 PM" src="https://github.com/edx/frontend-component-header-edx/assets/88369802/c2b3244e-cd8e-43da-b907-bec24b64516b">

2023-05-23 14:20 UTC, Syed-Ali-Abbas-Zaidi commented on src/learning-header/AuthenticatedUserDropdown.jsx
> +      <Badge className="px-2 mx-2" variant="warning">
We should add the `pill` prop over here too.

`<Badge className="px-2 mx-2" variant="warning" pill>`

2023-05-23 14:20 UTC, Syed-Ali-Abbas-Zaidi commented on src/Header.jsx
> +  const careerItemContent = <>{intl.formatMessage(messages['header.user.menu.career'])}&nbsp;&nbsp;<Badge className="px-2 mx-2" variant="warning">{intl.formatMessage(messages['header.user.menu.newAle
We can also remove both `&nbsp;` as the space between Career and New is already being handled in classname `px-2 mx-2`.

2023-05-23 19:12 UTC, krishatcher commented on src/Header.jsx
> +  const careerItemContent = <>{intl.formatMessage(messages['header.user.menu.career'])}&nbsp;&nbsp;<Badge className="px-2 mx-2" variant="warning">{intl.formatMessage(messages['header.user.menu.newAle
It's showing the rounded rectangle elsewhere, so I'd like to leave it that way here too.
![Desktop Screen Shot](https://github.com/edx/frontend-component-header-edx/assets/11753311/b3bd2486-a836-4d98-9ceb-7a27426832b5)

2023-05-23 19:13 UTC, krishatcher commented on src/Header.jsx
> +  const careerItemContent = <>{intl.formatMessage(messages['header.user.menu.career'])}&nbsp;&nbsp;<Badge className="px-2 mx-2" variant="warning">{intl.formatMessage(messages['header.user.menu.newAle
non-breaking space chars removed

2023-05-24 13:38 UTC, Syed-Ali-Abbas-Zaidi approved these changes
LGTM.

2023-05-26 18:16 UTC, krishatcher commented
This PR is part of a coordinated effort across multiple edX properties.  The full list of related PRs are included below for reference:

* https://github.com/edx/edx-themes/pull/794
* https://github.com/openedx/edx-platform/pull/32296
* https://github.com/edx/prospectus/pull/5345
* https://github.com/openedx/frontend-app-learner-dashboard/pull/152
* https://github.com/edx/edx-internal/pull/8428
* https://github.com/edx/frontend-component-header-edx/pull/375

2023-06-06 13:53 UTC, merged