fix: fixed ui issues of That's all your notifications
edx/frontend-component-header-edx pull request #473
Opened 2023-09-26 07:39 UTC by sundasnoreen12

[INF-1054](https://2u-internal.atlassian.net/browse/INF-1054)

**Description**
Fixed issues of Colors, font weights, font colors, check mark (can be exported from Figma), check mark size, check mark color etc.

**Screenshot**

![Screenshot 2023-09-26 at 12 38 55 PM](https://github.com/edx/frontend-component-header-edx/assets/72802712/903e85b0-abf0-42a0-86f3-d2b65949744d)

2023-09-26 08:33 UTC, awais-ansari requested changes

2023-09-26 08:33 UTC, awais-ansari commented on src/Notifications/NotificationSections.jsx
> +import CheckCircle from './icons/checkCircle';
Please add this icon in paragon then use it here.

2023-09-26 08:33 UTC, awais-ansari commented on src/Notifications/NotificationSections.jsx
> +            <div className="d-flex flex-row mx-auto color-gray">
use this class `text-gray-500` instead of custom class

2023-09-27 18:44 UTC, awais-ansari approved these changes

2023-09-28 01:28 UTC, muhammadadeeltajamul approved these changes

2023-09-28 05:52 UTC, merged