feat: added no notifition yet message bar
edx/frontend-component-header-edx pull request #475
Opened 2023-10-01 16:57 UTC by sundasnoreen12

[INF-1082](https://2u-internal.atlassian.net/browse/INF-1082)

**Description**

"No notification yet" message should be visible in the notification tray when there is no notification for the user.

Figma: [Notifications](https://www.figma.com/file/1WsIDaf9Alfy2r8eNYj6vX/Notifications?type=design&node-id=678-15078&mode=design)

**Screenshot**

<img width="555" alt="Screenshot 2023-10-01 at 9 56 02 PM" src="https://github.com/edx/frontend-component-header-edx/assets/72802712/1daa917d-d48c-45b2-b9a3-a08883533e0d">

2023-10-09 11:22 UTC, awais-ansari requested changes

2023-10-09 11:22 UTC, awais-ansari commented on src/Notifications/NotificationSections.jsx
> +  const [noNotificationDivHeight, setNoNotificationDivHeight] = useState(0);
No need to use state

2023-10-09 11:22 UTC, awais-ansari commented on src/Notifications/NotificationSections.jsx
> +  }, []);
use ref element instead of the document object.

2023-10-10 10:13 UTC, awais-ansari approved these changes

2023-10-10 10:15 UTC, muhammadadeeltajamul approved these changes

2023-10-10 10:16 UTC, merged