fix: notification tray height issues
edx/frontend-component-header-edx pull request #479
Opened 2023-10-04 10:01 UTC by sundasnoreen12

[INF-1052](https://2u-internal.atlassian.net/browse/INF-1052)

**Description**

Fixed following issues.

1. The notifications tray looks to be overlapping the NAV
2. When I scroll down the page I see a gap at the top, showing other LMS content:
3. There’s also a gap on the right, showing LMS content:

**Screenshots**
![Screenshot 2023-10-04 at 2 58 57 PM](https://github.com/edx/frontend-component-header-edx/assets/72802712/980b98bd-4973-4726-a554-759b8767905c)

![Screenshot 2023-10-04 at 2 59 06 PM](https://github.com/edx/frontend-component-header-edx/assets/72802712/dd2421c8-038d-4166-b192-f25ba5b9fc6d)

2023-10-09 11:35 UTC, awais-ansari requested changes

2023-10-09 11:35 UTC, awais-ansari commented on src/Notifications/index.jsx
>        dispatch(resetNotificationState());
simplify the logic. we do not need to use header, footer height to calculate the tray height.

2023-10-10 07:03 UTC, awais-ansari approved these changes

2023-10-10 08:41 UTC, muhammadadeeltajamul approved these changes

2023-10-10 08:42 UTC, merged