feat: added no notifition yet message bar
edx/frontend-component-header-edx pull request #493
Opened 2023-10-11 11:38 UTC by sundasnoreen12

[INF-1082](https://2u-internal.atlassian.net/browse/INF-1082)

Description

"No notification yet" message should be visible in the notification tray when there is no notification for the user.

Figma: [Notifications](https://www.figma.com/file/1WsIDaf9Alfy2r8eNYj6vX/Notifications?type=design&node-id=678-15078&mode=design)

Screenshot

![image](https://github.com/edx/frontend-component-header-edx/assets/72802712/d08d431e-85d3-4ee1-84ff-a3f074f62dfb)

2023-10-11 12:27 UTC, abdullahwaheed requested changes
Can you please add unit tests for the feature you are adding?

2023-10-11 13:33 UTC, abdullahwaheed commented on src/Notifications/notificationTabs.test.jsx
> -  it('Successfully selected reminder tab.', async () => {
don't remove this test, its decreasing [coverage](https://github.com/edx/frontend-component-header-edx/pull/493#issuecomment-1757499702)

2023-10-16 12:11 UTC, abdullahwaheed approved these changes

2023-10-19 12:08 UTC, awais-ansari requested changes

2023-10-19 12:08 UTC, awais-ansari commented on src/Notifications/index.jsx
> +                <NotificationTabs popoverHeaderRef={headerRef} notificationRef={popoverRef} />
create a context to pass these ref to nested children.

2023-10-19 14:34 UTC, awais-ansari requested changes

2023-10-19 14:34 UTC, awais-ansari commented on src/Notifications/index.jsx
> +/* eslint-disable react/jsx-no-constructed-context-values */
try to remove disable eslint

2023-10-20 07:41 UTC, awais-ansari approved these changes

2023-10-20 07:45 UTC, merged