feat: converted notification redux structure to context API
edx/frontend-component-header-edx pull request #598
Opened 2024-10-01 19:56 UTC by sundasnoreen12

[https://2u-internal.atlassian.net/browse/INF-1603](url)

**Description**
We have refactored the state management of the notification tray, transitioning from Redux to the Context API as the central store. This involved replacing all dispatch calls in the reducer with direct API calls, and managing server data through the Context provider. This change centralizes state management and resolves the issue of duplicate providers.

2024-10-02 18:30 UTC, awais-ansari requested changes
Create a context folder and move all the context there.

2024-10-08 22:15 UTC, jsnwesson commented on src/learning-header/AuthenticatedUserDropdown.jsx
> +  if (isNewNotificationViewEnabled) {
is there a reason why this condition can't be further up in LearningHeader.jsx?

2024-10-08 22:18 UTC, jsnwesson commented on src/learning-header/LearningHeader.jsx
> +            <AuthenticatedUserDropdown
Connected to my previous question in `AuthenticatedUserDropdown.jsx`, presenting both `AuthenticatedUserDropdown` and `NewAuthenticatedUserDropdown` here makes it look like both should be rendered. Even if this is all temporary and the plan is to remove the old dropdown, I think it'd make sense to keep the `if (isNewNotificationViewEnabled) ` condition here where it clearly demonstrates the repercussions of that boolean.

2024-10-08 22:21 UTC, jsnwesson commented on src/learning-header/New-AuthenticatedUserDropdown.jsx
> +const AuthenticatedUserDropdown = (props) => {
Shouldn't the name of the component here be `NewAuthenticatedUserDropdown` if the import in `LearningHeader.jsx` suggests it?

2024-10-09 07:32 UTC, sundasnoreen12 commented on src/learning-header/AuthenticatedUserDropdown.jsx
> +  if (isNewNotificationViewEnabled) {
The value of isNewNotificationViewEnabled is derived from the count API, which is called in AuthenticatedUserDropdown for the Redux structure and in NewAuthenticatedUserDropdown for the Context API structure. Moving this condition up to LearningHeader.jsx would mean calling the count API for both Redux and Context API structures. It's better to keep the current structure until we fully remove the Redux flow. Once the Redux architecture is phased out, we can then move this logic into LearningHeader for a cleaner setup. Is this make sense?

2024-10-09 07:33 UTC, sundasnoreen12 commented on src/learning-header/LearningHeader.jsx
> +            <AuthenticatedUserDropdown
Explanation in above comment

2024-10-11 00:18 UTC, jsnwesson commented on src/learning-header/AuthenticatedUserDropdown.jsx
> +  if (isNewNotificationViewEnabled) {
Ahh, that does make sense, I didn't catch that the Context API was the reason for writing it this way. Does this mean that there will eventually be a follow-up ticket to remove the old AuthenticatedUserDropdown and/or Redux, or is that a hope for eventual future work?

2024-10-11 00:43 UTC, jsnwesson approved these changes
One thing I'd suggest is that I noticed the test files for `NotificationRowItem`, `NotificationSections`, and `NotificationTabs` start with a lowercase letter, but that's probably more of a nit pick than something that would affect the tests passing/failing. 

Otherwise, this looks okay to me!

2024-10-11 13:51 UTC, adamstankiewicz reviewed
Left some comments, with a few clarifying higher level questions (e.g., around the boundaries between notifications and the authenticated user dropdown). Most of the comments pertain to styling/theming, addressing ESLint rules like `react-hooks/exhaustive-deps` vs. disabling them, and a sanity check around a possible race condition when marking notification as "read" when clicking a hyperlink.

2024-10-11 13:51 UTC, adamstankiewicz commented on src/new-notifications/notification.scss
> +  box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.15), 0px 2px 8px rgba(0, 0, 0, 0.15);
Use shadows from Paragon: https://paragon-openedx.netlify.app/foundations/elevation/

2024-10-11 13:51 UTC, adamstankiewicz commented on src/new-notifications/notification.scss
> +  margin-top: 7px !important;
Use spacing from Paragon: https://paragon-openedx.netlify.app/foundations/spacing/

2024-10-11 13:51 UTC, adamstankiewicz commented on src/learning-header/AuthenticatedUserDropdown.jsx
> +  if (isNewNotificationViewEnabled) {
Also wondering about the plan/eventual work to clean up the old `AuthenticatedUserDropdown` and the original `notifications` (and presumably rename the new ones to remove the `new` prefix, since they will not always be "new").

It's potentially worth considering treating the original `AuthenticatedUserDropdown` as "deprecated" (e.g., `DeprecatedAuthenticatedUserDropdown`) and have the new one keep the current name. Or perhaps consider it as a compound component instead, e.g.:

```
AuthenticatedUserDropdown (new one)
AuthenticatedUserDropdown.Deprecated (current/old one)
```

2024-10-11 13:51 UTC, adamstankiewicz commented on src/learning-header/AuthenticatedUserDropdown.jsx
> +  if (isNewNotificationViewEnabled) {
I also have a general question about the boundaries between notifications vs. the authenticated user dropdown. I'm not quite sure it makes sense to co-locate notifications within authenticated user dropdown as the notifications are a separate UI interaction from the authenticated user dropdown. Notifications and the authenticated user dropdown serve different purposes. I would think something like this below would have clearer boundaries/responsibilies:

```jsx
// LearningHeader

{authenticatedUser && (
  // new notifications, focused solely on notifications vs. notifications + user dropdown
  <Notifications ... />
)}
{showUserDropdown && authenticatedUser && (
  <AuthenticatedUserDropdown
    enterpriseLearnerPortalLink={enterpriseLearnerPortalLink}
    username={authenticatedUser.username}
    name={authenticatedUser.name}
    email={authenticatedUser.email}
  />
)}
{showUserDropdown && !authenticatedUser && (
  <AnonymousUserMenu />
)}
```

Or something like:

```jsx
// LearningHeader

{authenticatedUser && (
  <AuthenticatedUser />
)}
{!authenticatedUser && showUserDropdown && (
  <AnonymousUserMenu />
)}

// New component AuthenticatedUser
<>
  {/* new notifications, focused solely on notifications vs. notifications + user dropdown */}
  <Notifications ... />
  {showUserDropdown && (
    <AuthenticatedUserDropdown
      enterpriseLearnerPortalLink={enterpriseLearnerPortalLink}
      username={authenticatedUser.username}
      name={authenticatedUser.name}
      email={authenticatedUser.email}
    />
  )}
</>
```

2024-10-11 13:51 UTC, adamstankiewicz commented on src/learning-header/New-AuthenticatedUserDropdown.jsx
> +    <Dropdown.Item href="https://careers.edx.org/">
nit/curious: should this rely on config vs. hardcoding a URL? E.g., `getConfig().CAREERS_URL`. If it's common to all/most MFEs, it could be included in the common frontend config within edx-internal.

2024-10-11 13:51 UTC, adamstankiewicz commented on src/new-notifications/NotificationRowItem.jsx
> +              dangerouslySetInnerHTML={{ __html: content }}
[sanity check] Is it necessary to use `dangerouslySetInnerHTML` here vs. rendering `{content}` directly? If it is necessary, might consider sanitizing `content` to remove any risk of XSS injection, etc. (e.g., `DOMPurify.sanitize(content)`).

See more here: https://react.dev/reference/react-dom/components/common#dangerously-setting-the-inner-html

2024-10-11 13:51 UTC, adamstankiewicz commented on src/new-notifications/NotificationSections.jsx
> +
nit: extra line

2024-10-11 13:51 UTC, adamstankiewicz commented on src/new-notifications/NotificationTabs.jsx
> +      const data = await fetchNotificationList(appName);
[clarification/perhaps a future consideration] It seems there's 2 API calls need to fetch notifications (`fetchNotificationList` and `fetchAppsNotificationCount`). I'm wondering whether there would be an opportunity to be able to discern the list/count of notifications from the same API to avoid needing to orchestrate multiple related calls.

2024-10-11 13:51 UTC, adamstankiewicz commented on src/new-notifications/NotificationTabs.jsx
> +  // eslint-disable-next-line react-hooks/exhaustive-deps
As discussed in another comment, disabling this ESLint rule usually suggests a code smell.

2024-10-11 13:51 UTC, adamstankiewicz commented on src/new-notifications/NotificationTabs.jsx
> +          {appsId?.map((app) => (
nit: because of the conditional `appsId.length > 1`, the `?.` isn't need here.

2024-10-11 13:51 UTC, adamstankiewicz commented on src/new-notifications/NotificationTabs.jsx
> +              {appName === app && <NotificationSections />}
[clarification] What happens when `appName !== app`? Does this happen? Is an empty `<Tab/>` rendered as a result? Is this expected, or should the `Tab` itself not be rendered until `appName === app`?

2024-10-11 13:51 UTC, adamstankiewicz commented on src/new-notifications/index.jsx
> +/* eslint-disable react-hooks/exhaustive-deps */
Disabling this ESLint rule usually suggests a code smell(s) that should be mitigated, especially when disabled broadly, as it could lead to unintended behavior.

2024-10-11 13:51 UTC, adamstankiewicz commented on src/new-notifications/index.jsx
> +                  className={`d-flex justify-content-between px-4 pt-4 pb-14px m-0 border-0 text-primary-500 zIndex-2 font-size-18
Stick to the spacing values provided by the design system, wrt to the `pb-14px` class name. Either use `pb-2.5` (12px) or `pb-3` (16px).

2024-10-11 13:51 UTC, adamstankiewicz commented on src/new-notifications/index.jsx
> +                      className="icon-size-20 text-primary-500"
`<Icon size="sm" />` == `icon-size-20`

2024-10-11 13:51 UTC, adamstankiewicz commented on src/new-notifications/index.jsx
> +                  alt="feedback button"
I'm not sure this `Button` needs an `alt`? Usually only images need `alt`; I don't think screen readers would do anything with this `alt`, as it's non-standard for button elements.

If screen readers did read it aloud, given the button text is also `Feedback`, I believe it'd end up reading something like the following:

```
Button, feedback button, Feedback
```

Which is a bit repetitive vs. the more simple

```
Button, Feedback
```

2024-10-14 07:22 UTC, sundasnoreen12 commented on src/learning-header/AuthenticatedUserDropdown.jsx
> +  if (isNewNotificationViewEnabled) {
Yes, I have created the [follow-up ticket](https://2u-internal.atlassian.net/browse/INF-1658) to remove the Redux-related stuff.

2024-10-14 19:11 UTC, sundasnoreen12 commented on src/new-notifications/notification.scss
> +    height: 56px !important;
The size prop accepts the following values: 'xs' | 'sm' | 'md' | 'lg'. For sizes larger than these, styles or classes should be applied directly instead of using the size prop.

2024-10-14 19:30 UTC, sundasnoreen12 commented on src/learning-header/New-AuthenticatedUserDropdown.jsx
> +    <Dropdown.Item href="https://careers.edx.org/">
s per the Figma design, I needed to place the notification icon between the help button and the authenticated dropdown. That's why I included the notification module within the AuthenticatedUserDropdown file to achieve this layout.

2024-10-14 20:37 UTC, sundasnoreen12 commented on src/new-notifications/NotificationTabs.jsx
> +              {appName === app && <NotificationSections />}
The purpose of this check is to eliminate unnecessary DOM elements that are not visible to the user. If I were to remove the condition appName === app, the DOM would still contain empty sections for each tab that is not active. These sections would include the icon, the message No notifications yet, and the note When you receive notifications, they’ll show up here. Since the user is unaware of this UI, they might check the listings or the empty sections when switching to the respective tabs. To avoid unnecessary DOM elements, we have implemented this check.

2024-10-15 07:21 UTC, sundasnoreen12 commented on src/learning-header/New-AuthenticatedUserDropdown.jsx
> +  }, [window.location.href]);
I have removed // eslint-disable-next-line react-hooks/exhaustive-deps and replaced window.location.href with location.pathname. I also memoized the fetchNotificationData and fetchAppsNotificationCount functions. My goal is to trigger the count API call only when the pathname changes. However, including fetchAppsNotificationCount in the dependency array of fetchNotificationData was causing an infinite loop. To resolve this, I wrapped fetchAppsNotificationCount in a useCallback with an empty dependency array []. This ensures the function is created only once and does not change unnecessarily during re-renders, preventing an infinite loop in the useEffect.

2024-10-15 07:56 UTC, sundasnoreen12 commented on src/learning-header/New-AuthenticatedUserDropdown.jsx
> +    <Dropdown.Item href="https://careers.edx.org/">
#Also wondering about the plan/eventual work to clean up the old AuthenticatedUserDropdown and the original notifications (and presumably rename the new ones to remove the new prefix, since they will not always be "new").

It's potentially worth considering treating the original AuthenticatedUserDropdown as "deprecated" (e.g., DeprecatedAuthenticatedUserDropdown) and have the new one keep the current name. Or perhaps consider it as a compound component instead, e.g.:

AuthenticatedUserDropdown (new one)
AuthenticatedUserDropdown.Deprecated (current/old one)


My response to the above is that I will remove it after testing the Context API approach.

2024-10-15 12:23 UTC, sundasnoreen12 commented on src/new-notifications/NotificationTabs.jsx
> +      const data = await fetchNotificationList(appName);
We have intentionally separated the count API and the notification listing API to optimize performance. The count API is called after every route change to ensure that the count is always visible to the user, which improves engagement. In contrast, the notification listing API is triggered with each tab switch, as users may not always open the notifications tray. This design keeps the response size manageable; combining the notification list with the count API would increase the payload, making it heavier, especially during route changes. By maintaining this structure, we ensure efficient data retrieval tailored to user interactions without overwhelming the system with unnecessary data.

2024-10-16 09:51 UTC, sundasnoreen12 commented on src/new-notifications/NotificationTabs.jsx
> +  // eslint-disable-next-line react-hooks/exhaustive-deps
I want to trigger the fetchNotifications function only when appName changes, such as when switching tabs. However, ESLint suggests adding fetchNotificationList as a dependency, which causes a re-rendering issue. This happens because fetchNotificationList gets recreated on each render when included in the dependencies. To avoid this issue, I disabled the corresponding ESLint rule.

2024-10-18 11:15 UTC, adamstankiewicz commented on src/new-notifications/notification.scss
> +    height: 56px !important;
You are correct. That said, ideally, designs wouldn't be using non-standard icon sizes. If there is a new standard icon size proposed, it should be contributed upstream to the design system (both from a design + eng perspective). Unfortunately, often things end up hardcoded in consuming MFEs when they should be contributed upstream; though, in this case, I'm not sure if this is a one-off or a new standard size.

2024-10-18 11:19 UTC, adamstankiewicz commented on src/learning-header/AuthenticatedUserDropdown.jsx
> +  if (isNewNotificationViewEnabled) {
@sundasnoreen12 Any response to my above feedback/concern around the boundaries between `Notifications` and `AuthenticatedUserDropdown`...? The `AuthenticatedUserDropdown` ideally should remain as only the dropdown per the component name; mixing in `Notifications` is adding responsibilities to `AuthenticatedUserDropdown` unrelated to the user dropdown.

2024-10-18 11:26 UTC, adamstankiewicz commented on src/learning-header/AuthenticatedUserDropdown.jsx
> +  if (isNewNotificationViewEnabled) {
Ah, I see. I think you responded to that feedback in a different comment [thread](https://github.com/edx/frontend-component-header-edx/pull/598#discussion_r1799984407).

> As per the Figma design, I needed to place the notification icon between the help button and the authenticated dropdown. That's why I included the notification module within the AuthenticatedUserDropdown file to achieve this layout.

I understand the intent. I would also put that help button in the same category as not really belonging in `AuthenticatedUserDropdown`, as it's not related to the user dropdown itself; it's a distinct UI element/interaction.

Adding the help button back to my previous pseudocode snippet from above:

```jsx
// New component AuthenticatedUser
<>
  /* add help text before notifications */
  <a className="text-gray-700" href={`${getConfig().SUPPORT_URL}`}>{intl.formatMessage(messages.help)}</a>
  {/* new notifications, focused solely on notifications vs. notifications + user dropdown */}
  <Notifications ... />
  {showUserDropdown && (
    <AuthenticatedUserDropdown
      enterpriseLearnerPortalLink={enterpriseLearnerPortalLink}
      username={authenticatedUser.username}
      name={authenticatedUser.name}
      email={authenticatedUser.email}
    />
  )}
</>
```

Also worth noting, the `showLeftMargin: true` prop in `Notifications` likely wouldn't be needed if using `Stack` from `@openedx/paragon`. For example, if the React Fragment from the above snippet was changed to `Stack`:

```jsx
<Stack direction="horizontal" gap={4}>
  /* add help text before notifications */
  <a className="text-gray-700" href={`${getConfig().SUPPORT_URL}`}>{intl.formatMessage(messages.help)}</a>
  {/* new notifications, focused solely on notifications vs. notifications + user dropdown */}
  <Notifications ... />
  {showUserDropdown && (
    <AuthenticatedUserDropdown
      enterpriseLearnerPortalLink={enterpriseLearnerPortalLink}
      username={authenticatedUser.username}
      name={authenticatedUser.name}
      email={authenticatedUser.email}
    />
  )}
</Stack>
```

Using `Stack` would also ensure consistent spacing between all elements shown for authenticated users vs. having hardcoded `.ml-*` class names on the various subcomponents.

2024-10-18 19:21 UTC, sundasnoreen12 commented on src/learning-header/AuthenticatedUserDropdown.jsx
> +  if (isNewNotificationViewEnabled) {
Addressed Notification placement issue

2024-10-22 09:44 UTC, awais-ansari approved these changes

2024-10-24 09:33 UTC, sundasnoreen12 commented on src/new-notifications/NotificationRowItem.jsx
> +              dangerouslySetInnerHTML={{ __html: sanitizedContent }}
I believe this warning can be resolved by disabling the ESLint warning for dangerouslySetInnerHTML inline, where it's used.
like this {/* eslint-disable-next-line react/no-danger */}

2024-10-24 13:47 UTC, adamstankiewicz approved these changes
LGTM, with a couple comments. I appreciate all your iteration through the feedback! 🙌

2024-10-24 13:47 UTC, adamstankiewicz commented on src/learning-header/AuthenticatedUser.jsx
> +  children: PropTypes.arrayOf(PropTypes.node).isRequired,
nit: i believe this could be simplified to just `PropTypes.node.isRequired`

2024-10-24 13:47 UTC, adamstankiewicz commented on src/learning-header/AuthenticatedUser.jsx
> +};
nit: unnecessary if there are no default props :)

2024-10-24 13:47 UTC, adamstankiewicz commented on src/learning-header/AuthenticatedUser.jsx
> +export default React.memo(AuthenticatedUser);
[sanity check] Is the `React.memo` necessary here?

2024-10-25 07:49 UTC, merged